version: "3.9"

services:
  app:
    container_name: go-fiber-app
    build: .
    ports:
      - "3040:3040"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=goDb
    depends_on:
      - db
    networks:
      - go-fiber-net

  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: goDb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - go-fiber-net

networks:
  go-fiber-net:

volumes:
  postgres-data:

